// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: eatery.proto

package eatery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plantain   int32 `protobuf:"varint,1,opt,name=plantain,proto3" json:"plantain,omitempty"`
	Rice       int32 `protobuf:"varint,2,opt,name=rice,proto3" json:"rice,omitempty"`
	Beans      int32 `protobuf:"varint,3,opt,name=beans,proto3" json:"beans,omitempty"`
	Vegetables bool  `protobuf:"varint,4,opt,name=vegetables,proto3" json:"vegetables,omitempty"`
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eatery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eatery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_eatery_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRequest) GetPlantain() int32 {
	if x != nil {
		return x.Plantain
	}
	return 0
}

func (x *MenuRequest) GetRice() int32 {
	if x != nil {
		return x.Rice
	}
	return 0
}

func (x *MenuRequest) GetBeans() int32 {
	if x != nil {
		return x.Beans
	}
	return 0
}

func (x *MenuRequest) GetVegetables() bool {
	if x != nil {
		return x.Vegetables
	}
	return false
}

type MenuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eatery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eatery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_eatery_proto_rawDescGZIP(), []int{1}
}

func (x *MenuResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_eatery_proto protoreflect.FileDescriptor

var file_eatery_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x61, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x65, 0x61, 0x74, 0x65, 0x72, 0x79, 0x22, 0x73, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x61, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x65, 0x61, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x76,
	0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x76, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x4d,
	0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x41, 0x0a, 0x07, 0x65, 0x61, 0x72, 0x74, 0x65, 0x72, 0x79,
	0x12, 0x36, 0x0a, 0x07, 0x42, 0x75, 0x79, 0x47, 0x6f, 0x62, 0x65, 0x12, 0x13, 0x2e, 0x65, 0x61,
	0x74, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x65, 0x61, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x65, 0x61,
	0x74, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eatery_proto_rawDescOnce sync.Once
	file_eatery_proto_rawDescData = file_eatery_proto_rawDesc
)

func file_eatery_proto_rawDescGZIP() []byte {
	file_eatery_proto_rawDescOnce.Do(func() {
		file_eatery_proto_rawDescData = protoimpl.X.CompressGZIP(file_eatery_proto_rawDescData)
	})
	return file_eatery_proto_rawDescData
}

var file_eatery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eatery_proto_goTypes = []interface{}{
	(*MenuRequest)(nil),  // 0: eatery.MenuRequest
	(*MenuResponse)(nil), // 1: eatery.MenuResponse
}
var file_eatery_proto_depIdxs = []int32{
	0, // 0: eatery.eartery.BuyGobe:input_type -> eatery.MenuRequest
	1, // 1: eatery.eartery.BuyGobe:output_type -> eatery.MenuResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eatery_proto_init() }
func file_eatery_proto_init() {
	if File_eatery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eatery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eatery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eatery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eatery_proto_goTypes,
		DependencyIndexes: file_eatery_proto_depIdxs,
		MessageInfos:      file_eatery_proto_msgTypes,
	}.Build()
	File_eatery_proto = out.File
	file_eatery_proto_rawDesc = nil
	file_eatery_proto_goTypes = nil
	file_eatery_proto_depIdxs = nil
}
