# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import eatery_pb2 as eatery__pb2


class earteryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuyGobe = channel.unary_unary(
                '/eatery.eartery/BuyGobe',
                request_serializer=eatery__pb2.MenuRequest.SerializeToString,
                response_deserializer=eatery__pb2.MenuResponse.FromString,
                )


class earteryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuyGobe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_earteryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuyGobe': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyGobe,
                    request_deserializer=eatery__pb2.MenuRequest.FromString,
                    response_serializer=eatery__pb2.MenuResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eatery.eartery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class eartery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuyGobe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eatery.eartery/BuyGobe',
            eatery__pb2.MenuRequest.SerializeToString,
            eatery__pb2.MenuResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
