# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eatery.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65\x61tery.proto\x12\x06\x65\x61tery\"P\n\x0bMenuRequest\x12\x10\n\x08plantain\x18\x01 \x01(\x05\x12\x0c\n\x04rice\x18\x02 \x01(\x05\x12\r\n\x05\x62\x65\x61ns\x18\x03 \x01(\x05\x12\x12\n\nvegetables\x18\x04 \x01(\x08\"\x1f\n\x0cMenuResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x07\x65\x61rtery\x12\x36\n\x07\x42uyGobe\x12\x13.eatery.MenuRequest\x1a\x14.eatery.MenuResponse\"\x00\x42\nZ\x08./eateryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eatery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./eatery'
  _globals['_MENUREQUEST']._serialized_start=24
  _globals['_MENUREQUEST']._serialized_end=104
  _globals['_MENURESPONSE']._serialized_start=106
  _globals['_MENURESPONSE']._serialized_end=137
  _globals['_EARTERY']._serialized_start=139
  _globals['_EARTERY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
